CREATE TABLE ESTADO_USUARIO
(
    ID_ESTADO_USR NUMBER(3),
    NOMBRE VARCHAR2(100)
);
ALTER TABLE ESTADO_USUARIO ADD CONSTRAINT PK_EU PRIMARY KEY(ID_ESTADO_USR);



CREATE TABLE TIPO_MOVIMIENTO_USUARIO
(
    ID_TIPO_MOVIMIENTO NUMBER(3),
    DESCRIPCION VARCHAR2(100)
);
ALTER TABLE TIPO_MOVIMIENTO_USUARIO ADD CONSTRAINT PK_TMU PRIMARY KEY(ID_TIPO_MOVIMIENTO);



CREATE TABLE CAMPO_AFECTADO_USUARIO
(
    ID_CAMPO NUMBER(3),
    DESCRIPCION VARCHAR2(100)
);
ALTER TABLE CAMPO_AFECTADO_USUARIO ADD CONSTRAINT PK_CAU PRIMARY KEY(ID_CAMPO);




CREATE TABLE ROL_USUARIO
(
    ID_ROL_USUARIO NUMBER(3),
    DESCRIPCION VARCHAR2(100)
);
ALTER TABLE ROL_USUARIO ADD CONSTRAINT PK_IRU PRIMARY KEY(ID_ROL_USUARIO);



CREATE TABLE USUARIO_SISTEMA
(
    ID_USUARIO NUMBER(10),
    NOMBRES VARCHAR2(200),
    APELLIDOS VARCHAR2(100),
    ID_ESTADO_USR NUMBER(3),
    ID_ROL NUMBER(3),
    ACCESO VARCHAR2(200),
    ULTIMO_LOGIN TIMESTAMP,
    ID_ULTIMO_USUARIO_MODIFICADOR NUMBER(6)
);
ALTER TABLE USUARIO_SISTEMA ADD CONSTRAINT PK_US PRIMARY KEY(ID_USUARIO);
ALTER TABLE USUARIO_SISTEMA ADD CONSTRAINT FK_IEU FOREIGN KEY(ID_ESTADO_USR)
REFERENCES ESTADO_USUARIO(ID_ESTADO_USR);
ALTER TABLE USUARIO_SISTEMA ADD CONSTRAINT FK_IDR FOREIGN KEY(ID_ROL)
REFERENCES ROL_USUARIO(ID_ROL_USUARIO);
/*ALTER TABLE USUARIO_SISTEMA ADD CONSTRAINT FK_URMOD FOREIGN KEY(ID_ULTIMO_USUARIO_MODIFICADOR)
REFERENCES USUARIO_SISTEMA(ID_USUARIO);*/











CREATE TABLE ESTADO_CLIENTE
(
    ID_ESTADO_CLIENTE NUMBER(3),
    DESCRIPCION VARCHAR2(100)
);
ALTER TABLE ESTADO_CLIENTE ADD CONSTRAINT PK_EC PRIMARY KEY (ID_ESTADO_CLIENTE);



CREATE TABLE TIPO_MOVIMIENTO_CLIENTE
(
    ID_TIPO_MOVIMIENTO NUMBER(3),
    DESCRIPCION VARCHAR2(100)
);
ALTER TABLE TIPO_MOVIMIENTO_CLIENTE ADD CONSTRAINT PK_TMC PRIMARY KEY(ID_TIPO_MOVIMIENTO);


CREATE TABLE CAMPO_AFECTADO_CLIENTE
(
    ID_CAMPO_AFECTADO NUMBER(3),
    DESCRIPCION VARCHAR2(100)
);
ALTER TABLE CAMPO_AFECTADO_CLIENTE ADD CONSTRAINT PK_CAC PRIMARY KEY(ID_CAMPO_AFECTADO);



CREATE TABLE CLIENTE
(
    ID_CLIENTE NUMBER(10),
    NOMBRES VARCHAR2(200),
    APELLIDOS VARCHAR2(200),
    CORREO_INSTITUCIONAL VARCHAR2(100),
    ID_ESTADO_CLIENTE NUMBER(3),
    ID_ULT_USR_MODIFICADOR NUMBER(10)
);
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CFID PRIMARY KEY(ID_CLIENTE);
ALTER TABLE CLIENTE ADD CONSTRAINT FK_IDESTCL FOREIGN KEY(ID_ESTADO_CLIENTE) REFERENCES ESTADO_CLIENTE(ID_ESTADO_CLIENTE);
ALTER TABLE CLIENTE ADD CONSTRAINT FK_NUUMCF FOREIGN  KEY(ID_ULT_USR_MODIFICADOR) REFERENCES USUARIO_SISTEMA(ID_USUARIO);




CREATE TABLE SOFTWARE
(
    ID_SOFTWARE NUMBER(10),
    NOMBRE VARCHAR2(500),
    ID_ULTIMO_USUARIO_MODIFICADOR NUMBER(10)
);
ALTER TABLE SOFTWARE ADD CONSTRAINT PK_ID_SOFT PRIMARY KEY(ID_SOFTWARE);





CREATE TABLE ESTADO_VERSION
(
    ID_ESTADO_VERSION NUMBER(3),
    DESCRIPCION VARCHAR2(200)
);
ALTER TABLE ESTADO_VERSION ADD CONSTRAINT PK_ESTVERSION PRIMARY KEY(ID_ESTADO_VERSION);


CREATE TABLE VERSION_SOFTWARE
(
    ID_VERSION NUMBER(10),
    DESCRIPCION VARCHAR2(200),
    ID_SOFTWARE NUMBER(10),
    ID_ESTADO_VERSION NUMBER(3),
    FECHA_INICIO TIMESTAMP,
    FECHA_FINALIZACION TIMESTAMP,
    ULTIMO_USUARIO_MODIFICADOR NUMBER(10)
);
ALTER TABLE VERSION_SOFTWARE ADD CONSTRAINT PK_VSOFT PRIMARY KEY(ID_VERSION);
ALTER TABLE VERSION_SOFTWARE ADD CONSTRAINT FK_EVERSION FOREIGN KEY(ID_ESTADO_VERSION)
REFERENCES USUARIO_SISTEMA(ID_USUARIO);




CREATE TABLE ESTADO_DETALLE_SERVICIO
(
    ID_ESTADO_DETALLE_SERVICIO NUMBER(03),
    DESCRIPCION VARCHAR2(100)
);
ALTER TABLE ESTADO_DETALLE_SERVICIO ADD CONSTRAINT PK_IDEDSER PRIMARY KEY(ID_ESTADO_DETALLE_SERVICIO);




CREATE TABLE TIPO_MOVIMIENTO_BT_VSOFTWARE
(
    ID_TIPO_MOVIMIENTO NUMBER(3),
    DESCRIPCION VARCHAR2(100)
);
ALTER TABLE TIPO_MOVIMIENTO_BT_VSOFTWARE ADD CONSTRAINT PK_TMBS PRIMARY KEY(ID_TIPO_MOVIMIENTO);



CREATE TABLE CAMPO_AFECTADO_BT_VSOFTWARE
(
    ID_CAMPO NUMBER(3),
    DESCRIPCION VARCHAR2(100)
);
ALTER TABLE CAMPO_AFECTADO_BT_VSOFTWARE ADD CONSTRAINT PK_CABSOF PRIMARY KEY(ID_CAMPO);





CREATE TABLE DETALLE_SERVICIO
(
    ID_VERSION NUMBER(10),
    ID_CLIENTE NUMBER(10),
    ID_ESTADO_DETALLE_SERVICIO NUMBER(03),
    FECHA_INICIO_SERVICIO DATE,
    FECHA_INSTALACION DATE,
    FECHA_CESE_SERVICIO DATE,
    COSTO_TOTAL_SERVICIO NUMBER(6,2),
    ID_ULTIMO_USUARIO_MODIFICADOR NUMBER(10)
);
ALTER TABLE DETALLE_SERVICIO ADD CONSTRAINT PK_DSER PRIMARY KEY(ID_VERSION,ID_CLIENTE);
ALTER TABLE DETALLE_SERVICIO ADD CONSTRAINT FK_IDVERSION FOREIGN KEY(ID_VERSION) REFERENCES VERSION_SOFTWARE(ID_VERSION);
ALTER TABLE DETALLE_SERVICIO ADD CONSTRAINT FK_IDCLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);
ALTER TABLE DETALLE_SERVICIO ADD CONSTRAINT FK_IUUMOD FOREIGN KEY(ID_ULTIMO_USUARIO_MODIFICADOR) REFERENCES USUARIO_SISTEMA(ID_USUARIO);




/*bitácora para la tabla clientes*/
CREATE TABLE BITACORA_CLIENTE
(
    ID_OPERACION NUMBER(10),
    ID_CLIENTE_AFECTADO NUMBER(10),
    ID_TIPO_MOVIMIENTO NUMBER(3),
    VALOR_ANTIGUO VARCHAR2(200),
    VALOR_NUEVO VARCHAR2(200),
    ID_CAMPO_AFECTADO NUMBER(3),
    ID_USUARIO_RESP NUMBER(10),
    FECHA_MOVIMIENTO TIMESTAMP 
);
ALTER TABLE BITACORA_CLIENTE ADD CONSTRAINT PK_BICLI PRIMARY KEY(ID_OPERACION);
ALTER TABLE BITACORA_CLIENTE ADD CONSTRAINT FK_NCLI FOREIGN KEY(ID_CLIENTE_AFECTADO)
REFERENCES CLIENTE(ID_CLIENTE);
ALTER TABLE BITACORA_CLIENTE ADD CONSTRAINT FK_IDTIPMOV FOREIGN KEY(ID_TIPO_MOVIMIENTO)
REFERENCES TIPO_MOVIMIENTO_CLIENTE(ID_TIPO_MOVIMIENTO);
ALTER TABLE BITACORA_CLIENTE ADD CONSTRAINT FK_IDCAMAFEC
FOREIGN KEY(ID_CAMPO_AFECTADO) REFERENCES CAMPO_AFECTADO_CLIENTE(ID_CAMPO_AFECTADO);


CREATE TABLE BITACORA_USUARIO
(
    ID_TRANSACCION NUMBER(10),
    ID_USR_AFECTADO NUMBER(6),
    ID_TIPO_MOVIMIENTO NUMBER(3),
    ID_CAMPO_AFECTADO NUMBER(3),
    FECHA_MOVIMIENTO TIMESTAMP,
    ID_USUARIO_RESP NUMBER(10),
    VALOR_ANTERIOR VARCHAR(100),
    VALOR_NUEVO VARCHAR(100)
);
ALTER TABLE BITACORA_USUARIO ADD CONSTRAINT PK_BIUSR PRIMARY KEY (ID_TRANSACCION);
ALTER TABLE BITACORA_USUARIO ADD CONSTRAINT FK_IDUSRAFEC FOREIGN KEY(ID_USR_AFECTADO)
REFERENCES USUARIO_SISTEMA(ID_USUARIO);
ALTER TABLE BITACORA_USUARIO ADD CONSTRAINT FK_IDCAAFEC FOREIGN KEY (ID_CAMPO_AFECTADO)
REFERENCES CAMPO_AFECTADO_USUARIO(ID_CAMPO);
ALTER TABLE BITACORA_USUARIO ADD CONSTRAINT FK_ITPMU FOREIGN KEY (ID_TIPO_MOVIMIENTO)
REFERENCES TIPO_MOVIMIENTO_USUARIO(ID_TIPO_MOVIMIENTO);




CREATE TABLE BITACORA_DETALLE_SERVICIO
(
    ID_TRANSACCION NUMBER(10),
    ID_VERSION NUMBER(10),
    ID_CLIENTE NUMBER(10),
    ID_TIPO_MOVIMIENTO NUMBER(3),
    ID_CAMPO_AFECTADO NUMBER(3),
    FECHA_MOVIMIENTO TIMESTAMP,
    ID_USUARIO_RESP NUMBER(6),
    VALOR_ANTERIOR VARCHAR(100),
    VALOR_NUEVO VARCHAR(100)
);
ALTER TABLE BITACORA_DETALLE_SERVICIO ADD CONSTRAINT PK_ID_TRANSACCION PRIMARY KEY(ID_TRANSACCION);
ALTER TABLE BITACORA_DETALLE_SERVICIO ADD CONSTRAINT FK_DETALLE_SERVICIO FOREIGN KEY(ID_VERSION,ID_CLIENTE)
REFERENCES DETALLE_SERVICIO(ID_VERSION,ID_CLIENTE);
ALTER TABLE BITACORA_DETALLE_SERVICIO ADD CONSTRAINT FK_TMOBDS FOREIGN KEY(ID_TIPO_MOVIMIENTO)
REFERENCES TIPO_MOVIMIENTO_BT_VSOFTWARE(ID_TIPO_MOVIMIENTO);
ALTER TABLE BITACORA_DETALLE_SERVICIO ADD CONSTRAINT FK_ICAFECTADO FOREIGN KEY(ID_CAMPO_AFECTADO)
REFERENCES CAMPO_AFECTADO_BT_VSOFTWARE(ID_CAMPO);





