/*tabla tipo_movimiento_usuario:*/
CREATE TABLE ESTADO_USUARIO
(
    ID_ESTADO_USR INT(3),
    NOMBRE VARCHAR(100)
);
ALTER TABLE ESTADO_USUARIO ADD CONSTRAINT PK_EU PRIMARY KEY(ID_ESTADO_USR);
ALTER TABLE ESTADO_USUARIO MODIFY COLUMN ID_ESTADO_USR INT(3) AUTO_INCREMENT;



CREATE TABLE ESTADO_CLIENTE
(
    ID_ESTADO_CLIENTE INT(3),
    DESCRIPCION VARCHAR(100)
);
ALTER TABLE ESTADO_CLIENTE ADD CONSTRAINT PK_EC PRIMARY KEY (ID_ESTADO_CLIENTE);
ALTER TABLE ESTADO_CLIENTE MODIFY COLUMN ID_ESTADO_CLIENTE INT(3) AUTO_INCREMENT;





CREATE TABLE TIPO_MOVIMIENTO_USUARIO
(
    ID_TIPO_MOVIMIENTO INT(3),
    DESCRIPCION VARCHAR(100)
);
ALTER TABLE TIPO_MOVIMIENTO_USUARIO ADD CONSTRAINT PK_TMU PRIMARY KEY(ID_TIPO_MOVIMIENTO);
ALTER TABLE TIPO_MOVIMIENTO_USUARIO MODIFY COLUMN ID_TIPO_MOVIMIENTO INT(3) AUTO_INCREMENT;


CREATE TABLE CAMPO_AFECTADO_USUARIO
(
    ID_CAMPO INT(3),
    DESCRIPCION VARCHAR(100)
);
ALTER TABLE CAMPO_AFECTADO_USUARIO ADD CONSTRAINT PK_CAU PRIMARY KEY(ID_CAMPO);
ALTER TABLE CAMPO_AFECTADO_USUARIO MODIFY COLUMN ID_CAMPO INT(3) AUTO_INCREMENT;





CREATE TABLE ROL_USUARIO
(
    ID_ROL_USUARIO INT(3),
    DESCRIPCION VARCHAR(100)
);
ALTER TABLE ROL_USUARIO ADD CONSTRAINT PK_IRU PRIMARY KEY(ID_ROL_USUARIO);
ALTER TABLE ROL_USUARIO MODIFY COLUMN ID_ROL_USUARIO INT(3) AUTO_INCREMENT;





CREATE TABLE TIPO_MOVIMIENTO_CLIENTE
(
    ID_TIPO_MOVIMIENTO INT(3),
    DESCRIPCION VARCHAR(100)
);
ALTER TABLE TIPO_MOVIMIENTO_CLIENTE ADD CONSTRAINT PK_TMC PRIMARY KEY(ID_TIPO_MOVIMIENTO);
ALTER TABLE TIPO_MOVIMIENTO_CLIENTE MODIFY ID_TIPO_MOVIMIENTO INT(3) AUTO_INCREMENT;



CREATE TABLE CAMPO_AFECTADO_CLIENTE
(
    ID_CAMPO_AFECTADO INT(3),
    DESCRIPCION VARCHAR(100)
);
ALTER TABLE CAMPO_AFECTADO_CLIENTE ADD CONSTRAINT PK_CAC PRIMARY KEY(ID_CAMPO_AFECTADO);
ALTER TABLE CAMPO_AFECTADO_CLIENTE MODIFY COLUMN ID_CAMPO_AFECTADO INT(3) AUTO_INCREMENT;















CREATE TABLE CONSUMIDOR_FINAL
(
    ID_CLIENTE INT(10),
    NOMBRES VARCHAR(200),
    APELLIDOS VARCHAR(200),
    CORREO_INSTITUCIONAL VARCHAR(100),
    ID_SECCION INT(3),
    ID_ESTADO_CLIENTE INT(3),
    FECHA_CREACION TIMESTAMP,
    ID_ULT_USR_MODIFICADOR INT(10)
);
ALTER TABLE CONSUMIDOR_FINAL ADD CONSTRAINT PK_CFID PRIMARY KEY(ID_CLIENTE);
ALTER TABLE CONSUMIDOR_FINAL ADD CONSTRAINT FK_IDSEC FOREIGN KEY(ID_SECCION) REFERENCES SECCION(ID_SECCION);
ALTER TABLE CONSUMIDOR_FINAL ADD CONSTRAINT FK_IDESTCL FOREIGN KEY(ID_ESTADO_CLIENTE) REFERENCES ESTADO_CLIENTE(ID_ESTADO_CLIENTE);
ALTER TABLE CONSUMIDOR_FINAL ADD CONSTRAINT FK_NUUMCF FOREIGN  KEY(ID_ULT_USR_MODIFICADOR) REFERENCES USUARIO_SISTEMA(ID_USUARIO);



CREATE TABLE USUARIO_SISTEMA
(
    ID_USUARIO INT(10),
    NOMBRES VARCHAR(200),
    APELLIDOS VARCHAR(100),
    ID_ESTADO_USR INT(3),
    ID_ROL INT(3),
    ACCESO VARCHAR(200),
    ULTIMO_LOGIN TIMESTAMP,
    ULTIMO_USUARIO_MODIFICADOR INT(6)
);
ALTER TABLE USUARIO_SISTEMA ADD CONSTRAINT PK_US PRIMARY KEY(ID_USUARIO);
ALTER TABLE USUARIO_SISTEMA ADD CONSTRAINT FK_IEU FOREIGN KEY(ID_ESTADO_USR)
REFERENCES ESTADO_USUARIO(ID_ESTADO_USR);
ALTER TABLE USUARIO_SISTEMA ADD CONSTRAINT FK_IDR FOREIGN KEY(ID_ROL)
REFERENCES ROL_USUARIO(ID_ROL);
/*ALTER TABLE USUARIO_SISTEMA ADD CONSTRAINT FK_URMOD FOREIGN KEY(ULTIMO_USUARIO_MODIFICADOR)
REFERENCES USUARIO_SISTEMA(ID_USUARIO);*/




/*bitácora para la tabla clientes*/
CREATE TABLE BITACORA_CLIENTE
(
    ID_OPERACION INT(10),
    ID_CLIENTE INT(10),
    ID_TIPO_MOVIMIENTO INT(3),
    VALOR_ANTIGUO VARCHAR(200),
    VALOR_NUEVO VARCHAR(200),
    ID_CAMPO_AFECTADO INT(3),
    ID_USUARIO_RESP INT(10),
    FECHA_MOVIMIENTO TIMESTAMP 
);
ALTER TABLE BITACORA_CLIENTE ADD CONSTRAINT PK_BICLI PRIMARY KEY(ID_OPERACION);
ALTER TABLE BITACORA_CLIENTE MODIFY COLUMN ID_OPERACION INT(10) AUTO_INCREMENT;
ALTER TABLE BITACORA_CLIENTE ADD CONSTRAINT FK_NCLI FOREIGN KEY(ID_CLIENTE)
REFERENCES CONSUMIDOR_FINAL(ID_CLIENTE);
ALTER TABLE BITACORA_CLIENTE ADD CONSTRAINT FK_IDTIPMOV FOREIGN KEY(ID_TIPO_MOVIMIENTO)
REFERENCES TIPO_MOVIMIENTO_CLIENTE(ID_TIPO_MOVIMIENTO);
ALTER TABLE BITACORA_CLIENTE ADD CONSTRAINT FK_IDCAMAFEC
FOREIGN KEY(ID_CAMPO_AFECTADO) REFERENCES CAMPO_AFECTADO_CLIENTE(ID_CAMPO_AFECTADO);





